name: Builds

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build primary executable
      run: make

    - name: exercise install
      run: sudo make install

    - name: exercise uninstall
      run: sudo make uninstall

    - name: clean up primary build
      run: make clean

    - name: build test executable
      run: make test

    - name: clean up test build
      run: make test_clean

    - name: build debug executable
      run: make debug

    - name: clean up debug build
      run: make debug_clean
