name: make and exercise

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build executable
      run: make

    - name: test install
      run: sudo make install

    - name: test uninstall
      run: sudo make uninstall

    - name: clean up
      run: make clean
