name: Run Unit Tests

on:
  push:
    paths:
      - "Makefile"
      - "src/**"
      - "main.c"
      - "test/**"

  pull_request:
    branches:
      - "main"
    paths:
      - "Makefile"
      - "src/**"
      - "main.c"
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build test executables
        run: make test

      - name: Clean up test executable
        run: make test_clean
