name: Run Unit Tests

on:
  push:
    paths:
      - "Makefile"
      - "src/**"
      - "main.c"
      - "test/**"

  pull_request:
    branches:
      - "main"
    paths:
      - "Makefile"
      - "src/**"
      - "main.c"
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mmv
        uses: actions/checkout@v3

      - name: Clone test framework
        uses: actions/checkout@v3
        with:
          repository: ThrowTheSwitch/Unity
          path: Unity

      - name: Set up directory
        run: mv ./Unity/src/* test

      - name: Build test executables
        run: make test

      - name: Clean up test executable
        run: make test_clean
