name: Valgrind

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  execute_valgrind:
    runs-on: ubuntu-latest
    env:
        Test_files_dir: test_dir
        Utils: .github/utils

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev

    - name: create test files
      run: sh "$Utils"/init_files.sh "$Test_files_dir" 10

    - name: build debug executable
      run: |
        make debug
        valgrind --leak-check=full --trace-children=yes --track-origins=yes \
            --show-leak-kinds=all -s ./debug_mmv "$Test_files_dir"/test*
