name: Valgrind

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  execute_valgrind:
    runs-on: ubuntu-latest
    env:
        test_files_dir: test_dir
        utils: .github/utils

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get -y install valgrind

    - name: Create test files
      run: sh "$utils"/init_files.sh "$test_files_dir" 10

    - name: Build debug executable
      run: make debug

    - name: Execute Valgrind
      run: valgrind --leak-check=full --trace-children=yes --track-origins=yes \
            --show-leak-kinds=all -s ./debug_mmv "$test_files_dir"/test*
